version: "3.9"

services:
  bot:
    build:
      context: ./bot
    container_name: school_bot
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: always

  admin:
    build:
      context: ./admin
    container_name: school_admin
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    restart: always
